/* arch/arm/mach-exynos/include/mach/regs-clock-exynos3.h
 *
 * Copyright (c) 2014 Samsung Electronics Co., Ltd.
 * http://www.samsung.com
 *
 * EXYNOS3 - Clock register definitions
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __ASM_ARCH_REGS_CLOCK_EXYNOS3_H
#define __ASM_ARCH_REGS_CLOCK_EXYNOS3_H __FILE__

#include <plat/cpu.h>
#include <mach/map.h>

#define EXYNOS3_CLK_BUS_TOP_REG(x)	(EXYNOS3_VA_CMU_BUS_TOP + (x))
#define EXYNOS3_CPU_ISP_REG(x)		(EXYNOS3_VA_CMU_CPU_ISP + (x))
#define EXYNOS3_MIF_R_REG(x)		(EXYNOS3_VA_CMU_ACP + (x))
#define EXYNOS3_MIF_L_REG(x)		(EXYNOS3_VA_CMU_DMC + (x))

/*LEFT_BUS */
#define SRC_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4200)
#define MUX_STAT_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4400)
#define DIV_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4500)
#define DIV_STAT_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4600)
#define GATE_BUS_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4700)
#define GATE_IP_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4800)
#define OUT_CMU_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4A00)
#define OUT_CMU_LEFTBUS_DIV_STAT	EXYNOS3_CLK_BUS_TOP_REG(0x4A04)

#define SRC_TOP0			EXYNOS3_CLK_BUS_TOP_REG(0xC210)
#define SRC_TOP1			EXYNOS3_CLK_BUS_TOP_REG(0xC214)
#define SRC_CAM				EXYNOS3_CLK_BUS_TOP_REG(0xC220)
#define SRC_MFC				EXYNOS3_CLK_BUS_TOP_REG(0xC228)
#define SRC_G3D				EXYNOS3_CLK_BUS_TOP_REG(0xC22C)
#define SRC_LCD				EXYNOS3_CLK_BUS_TOP_REG(0xC234)
#define SRC_ISP				EXYNOS3_CLK_BUS_TOP_REG(0xC238)
#define SRC_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC250)
#define SRC_PERIL1			EXYNOS3_CLK_BUS_TOP_REG(0xC254)

#define EXYNOS3_CLKSRC_MASK_TOP		EXYNOS3_CLK_BUS_TOP_REG(0xC310)

#define SRC_MASK_CAM			EXYNOS3_CLK_BUS_TOP_REG(0xC320)
#define SRC_MASK_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC334)
#define SRC_MASK_ISP			EXYNOS3_CLK_BUS_TOP_REG(0xC338)
#define EXYNOS3_CLKSRC_MASK_FSYS	EXYNOS3_CLK_BUS_TOP_REG(0xC340)
#define SRC_MASK_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC350)
#define SRC_MASK_PERIL1			EXYNOS3_CLK_BUS_TOP_REG(0xC354)

#define DIV_TOP				EXYNOS3_CLK_BUS_TOP_REG(0xC510)
#define DIV_CAM				EXYNOS3_CLK_BUS_TOP_REG(0xC520)
#define DIV_MFC				EXYNOS3_CLK_BUS_TOP_REG(0xC528)
#define DIV_G3D				EXYNOS3_CLK_BUS_TOP_REG(0xC52C)
#define DIV_LCD				EXYNOS3_CLK_BUS_TOP_REG(0xC534)
#define DIV_ISP				EXYNOS3_CLK_BUS_TOP_REG(0xC538)
#define DIV_PERIL0			EXYNOS3_CLK_BUS_TOP_REG(0xC550)
#define DIV_PERIL1			EXYNOS3_CLK_BUS_TOP_REG(0xC554)
#define DIV_PERIL4			EXYNOS3_CLK_BUS_TOP_REG(0xC560)
#define DIV_PERIL5			EXYNOS3_CLK_BUS_TOP_REG(0xC564)
#define EXYNOS3_CLKDIV_STAT_LCD		EXYNOS3_CLK_BUS_TOP_REG(0xC634)

#define GATE_BUS_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC734)
#define GATE_BUS_PERIL			EXYNOS3_CLK_BUS_TOP_REG(0xC750)
#define GATE_SCLK_CAM			EXYNOS3_CLK_BUS_TOP_REG(0xC820)
#define GATE_SCLK_MFC			EXYNOS3_CLK_BUS_TOP_REG(0xC828)
#define GATE_SCLK_G3D			EXYNOS3_CLK_BUS_TOP_REG(0xC82C)
#define GATE_SCLK_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC834)
#define GATE_SCLK_ISP			EXYNOS3_CLK_BUS_TOP_REG(0xC838)
#define GATE_SCLK_PERIL			EXYNOS3_CLK_BUS_TOP_REG(0xC850)


#define GATE_IP_CAM			EXYNOS3_CLK_BUS_TOP_REG(0xC920)
#define GATE_IP_MFC			EXYNOS3_CLK_BUS_TOP_REG(0xC928)
#define GATE_IP_G3D			EXYNOS3_CLK_BUS_TOP_REG(0xC92C)
#define GATE_IP_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC934)
#define GATE_IP_PERIL			EXYNOS3_CLK_BUS_TOP_REG(0xC950)
#define SRC_MASK_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xC340)
#define DIV_FSYS0			EXYNOS3_CLK_BUS_TOP_REG(0xc540)
#define DIV_FSYS1			EXYNOS3_CLK_BUS_TOP_REG(0xc544)
#define DIV_FSYS2			EXYNOS3_CLK_BUS_TOP_REG(0xc548)
#define GATE_BUS_FSYS0			EXYNOS3_CLK_BUS_TOP_REG(0xc740)
#define GATE_IP_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xc940)
#define SRC_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xc240)
#define GATE_SCLK_FSYS			EXYNOS3_CLK_BUS_TOP_REG(0xC840)

#define EXYNOS3_CLKSRC_MASK_LCD			SRC_MASK_LCD
#define EXYNOS3_CLKSRC_MASK_CAM			SRC_MASK_CAM
#define EXYNOS3_CLKSRC_MASK_ISP			SRC_MASK_ISP
#define EXYNOS3_CLKSRC_MASK_PERIL0		SRC_MASK_PERIL0
#define EXYNOS3_CLKSRC_MASK_PERIL1		SRC_MASK_PERIL1

#define EXYNOS3_CLKDIV_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_GPL_MASK	\
	(0x7 << EXYNOS3_CLKDIV_GPL_SHIFT)
#define EXYNOS3_CLKDIV_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_GDL_MASK	\
	(0xF << EXYNOS3_CLKDIV_GDL_SHIFT)

#define EXYNOS3_CLKDIV_STAT_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_STAT_GPL_MASK	\
		(0x1 << EXYNOS3_CLKDIV_STAT_GPL_SHIFT)
#define EXYNOS3_CLKDIV_STAT_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_GDL_MASK	\
	(0x1 << EXYNOS3_CLKDIV_STAT_GDL_SHIFT)

#define EXYNOS3_CLKGATE_BUS_CAM0		EXYNOS3_CLK_BUS_TOP_REG(0xC720)
#define EXYNOS3_CLKGATE_BUS_MFC			EXYNOS3_CLK_BUS_TOP_REG(0xC728)
#define EXYNOS3_CLKGATE_BUS_G3D			EXYNOS3_CLK_BUS_TOP_REG(0xC72C)
#define EXYNOS3_CLKGATE_BUS_LCD			EXYNOS3_CLK_BUS_TOP_REG(0xC734)
#define EXYNOS3_CLKGATE_BUS_CAM1		EXYNOS3_CLK_BUS_TOP_REG(0xC738)

#define EXYNOS3_CLKGATE_SCLK_CAM		EXYNOS3_CLK_BUS_TOP_REG(0xC820)
#define EXYNOS3_CLKGATE_SCLK_LCD		EXYNOS3_CLK_BUS_TOP_REG(0xC834)
#define EXYNOS3_CLKGATE_SCLK_TOP_ISP		EXYNOS3_CLK_BUS_TOP_REG(0xC838)

#define EXYNOS3_CLKGATE_IP_G3D			GATE_IP_G3D
#define EXYNOS3_CLKGATE_IP_LCD			GATE_IP_LCD
#define EXYNOS3_CLKGATE_IP_CAM			GATE_IP_CAM
#define EXYNOS3_CLKGATE_IP_MFC			GATE_IP_MFC
#define EXYNOS3_CLKGATE_IP_ISP			EXYNOS3_CLK_BUS_TOP_REG(0xC938)
#define EXYNOS3_CLKGATE_IP_FSYS                 EXYNOS3_CLK_BUS_TOP_REG(0xC940)
#define EXYNOS3_CLKGATE_IP_PERIL                EXYNOS3_CLK_BUS_TOP_REG(0xC950)

/* RIGHT_BUS */
#define SRC_RIGHTBUS				EXYNOS3_CLK_BUS_TOP_REG(0x8200)
#define EXYNOS3_CLKMUX_STAT_RIGHTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x8400)
#define DIV_RIGHTBUS				EXYNOS3_CLK_BUS_TOP_REG(0x8500)
#define EXYNOS3_CLKDIV_STAT_RIGHTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x8600)
#define EXYNOS3_CLKGATE_BUS_RIGHTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x8700)
#define GATE_BUS_PERIR				EXYNOS3_CLK_BUS_TOP_REG(0x8760)
#define GATE_IP_RIGHTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x8800)
#define GATE_IP_PERIR				EXYNOS3_CLK_BUS_TOP_REG(0x8960)
#define EXYNOS3_CLKOUT_CMU_RIGHTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x8A00)
#define EXYNOS3_CLKOUT_CMU_RIGHTBUS_DIV_STAT	EXYNOS3_CLK_BUS_TOP_REG(0x8A04)

/*CPU-CMU / ISP */
#define EXYNOS3_CLKSRC_CPU_MUXCORE_SHIFT	(16)
#define EXYNOS3_CLKMUX_STATCPU_MUXCORE_MASK	(0x7 << EXYNOS4_CLKSRC_CPU_MUXCORE_SHIFT)

#define EXYNOS3_CLKDIV_CPU0_CORE_SHIFT		(0)
#define EXYNOS3_CLKDIV_CPU0_CORE_MASK		(0x7 << EXYNOS3_CLKDIV_CPU0_CORE_SHIFT)
#define EXYNOS3_CLKDIV_CPU0_COREM0_SHIFT	(4)
#define EXYNOS3_CLKDIV_CPU0_COREM0_MASK		(0x7 << EXYNOS3_CLKDIV_CPU0_COREM0_SHIFT)
#define EXYNOS3_CLKDIV_CPU0_ATB_SHIFT		(16)
#define EXYNOS3_CLKDIV_CPU0_ATB_MASK		(0x7 << EXYNOS3_CLKDIV_CPU0_ATB_SHIFT)
#define EXYNOS3_CLKDIV_CPU0_PCLKDBG_SHIFT	(20)
#define EXYNOS3_CLKDIV_CPU0_PCLKDBG_MASK	(0x7 << EXYNOS3_CLKDIV_CPU0_PCLKDBG_SHIFT)
#define EXYNOS3_CLKDIV_CPU0_APLL_SHIFT		(24)
#define EXYNOS3_CLKDIV_CPU0_APLL_MASK		(0x7 << EXYNOS3_CLKDIV_CPU0_APLL_SHIFT)
#define EXYNOS3_CLKDIV_CPU0_CORE2_SHIFT		28
#define EXYNOS3_CLKDIV_CPU0_CORE2_MASK		(0x7 << EXYNOS3_CLKDIV_CPU0_CORE2_SHIFT)

#define EXYNOS3_CLKDIV_CPU1_COPY_SHIFT		0
#define EXYNOS3_CLKDIV_CPU1_COPY_MASK		(0x7 << EXYNOS3_CLKDIV_CPU1_COPY_SHIFT)
#define EXYNOS3_CLKDIV_CPU1_HPM_SHIFT		4
#define EXYNOS3_CLKDIV_CPU1_HPM_MASK		(0x7 << EXYNOS3_CLKDIV_CPU1_HPM_SHIFT)

#define EXYNOS3_CLKDIV_LEFTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x4500)
#define EXYNOS3_CLKDIV_STAT_LEFTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x4600)

#define EXYNOS3_CLKDIV_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_GPL_MASK			(0x7 << EXYNOS3_CLKDIV_GPL_SHIFT)
#define EXYNOS3_CLKDIV_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_GDL_MASK			(0xF << EXYNOS3_CLKDIV_GDL_SHIFT)

#define EXYNOS3_CLKDIV_STAT_GPL_SHIFT		(4)
#define EXYNOS3_CLKDIV_STAT_GPL_MASK		(0x1 << EXYNOS3_CLKDIV_STAT_GPL_SHIFT)
#define EXYNOS3_CLKDIV_STAT_GDL_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_GDL_MASK		(0x1 << EXYNOS3_CLKDIV_STAT_GDL_SHIFT)

#define EXYNOS3_CLKDIV_TOP			DIV_TOP
#define EXYNOS3_CLKDIV_STAT_TOP			EXYNOS3_CLK_BUS_TOP_REG(0xC610)

#define EXYNOS3_CLKDIV_ACLK_400_SHIFT		(24)
#define EXYNOS3_CLKDIV_ACLK_400_MASK		(0x7 << EXYNOS3_CLKDIV_ACLK_400_SHIFT)
#define EXYNOS3_CLKDIV_ACLK_200_SHIFT		(12)
#define EXYNOS3_CLKDIV_ACLK_200_MASK		(0x7 << EXYNOS3_CLKDIV_ACLK_200_SHIFT)
#define EXYNOS3_CLKDIV_ACLK_160_SHIFT		(8)
#define EXYNOS3_CLKDIV_ACLK_160_MASK		(0x7 << EXYNOS3_CLKDIV_ACLK_160_SHIFT)
#define EXYNOS3_CLKDIV_ACLK_100_SHIFT		(4)
#define EXYNOS3_CLKDIV_ACLK_100_MASK		(0xF << EXYNOS3_CLKDIV_ACLK_100_SHIFT)
#define EXYNOS3_CLKDIV_ACLK_266_SHIFT		(0)
#define EXYNOS3_CLKDIV_ACLK_266_MASK		(0x7 << EXYNOS3_CLKDIV_ACLK_266_SHIFT)

#define EXYNOS3_CLKDIV_STAT_ACLK_400_SHIFT	(24)
#define EXYNOS3_CLKDIV_STAT_ACLK_400_MASK	(0x1 << EXYNOS3_CLKDIV_STAT_ACLK_400_SHIFT)
#define EXYNOS3_CLKDIV_STAT_MPLL_PRE_SHIFT	(20)
#define EXYNOS3_CLKDIV_STAT_MPLL_200_MASK	(0x1 << EXYNOS3_CLKDIV_STAT_MPLL_PRE_SHIFT)
#define EXYNOS3_CLKDIV_STAT_EBI_SHIFT		(16)
#define EXYNOS3_CLKDIV_STAT_EBI_MASK		(0x1 << EXYNOS3_CLKDIV_EBI_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACLK_200_SHIFT	(12)
#define EXYNOS3_CLKDIV_STAT_ACLK_200_MASK	(0x1 << EXYNOS3_CLKDIV_ACLK_200_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACLK_160_SHIFT	(8)
#define EXYNOS3_CLKDIV_STAT_ACLK_160_MASK	(0x1 << EXYNOS3_CLKDIV_ACLK_160_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACLK_100_SHIFT	(4)
#define EXYNOS3_CLKDIV_STAT_ACLK_100_MASK	(0x1 << EXYNOS3_CLKDIV_ACLK_100_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACLK_266_SHIFT	(0)
#define EXYNOS3_CLKDIV_STAT_ACLK_266_MASK	(0x1 << EXYNOS3_CLKDIV_ACLK_266_SHIFT)

#define EXYNOS3_CLKDIV_MFC			DIV_MFC
#define EXYNOS3_CLKDIV_STAT_MFC			EXYNOS3_CLK_BUS_TOP_REG(0xC628)

#define EXYNOS3_CLKDIV_MFC_SHIFT		(0)
#define EXYNOS3_CLKDIV_MFC_MASK			(0x7 << EXYNOS3_CLKDIV_MFC_SHIFT)
#define EXYNOS3_CLKDIV_STAT_MFC_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_MFC_MASK		(0x1 << EXYNOS3_CLKDIV_STAT_MFC_SHIFT)

/* RIGHT_BUS */
#define EXYNOS3_CLKDIV_RIGHTBUS			EXYNOS3_CLK_BUS_TOP_REG(0x8500)
#define EXYNOS3_CLKDIV_STAT_RIGHTBUS		EXYNOS3_CLK_BUS_TOP_REG(0x8600)

#define EXYNOS3_CLKDIV_GPR_SHIFT		(4)
#define EXYNOS3_CLKDIV_GPR_MASK			(0x7 << EXYNOS3_CLKDIV_GPR_SHIFT)
#define EXYNOS3_CLKDIV_GDR_SHIFT		(0)
#define EXYNOS3_CLKDIV_GDR_MASK			(0xF << EXYNOS3_CLKDIV_GDR_SHIFT)

#define EXYNOS3_CLKDIV_STAT_GPR_SHIFT		(4)
#define EXYNOS3_CLKDIV_STAT_GPR_MASK		(0x1 << EXYNOS3_CLKDIV_STAT_GPR_SHIFT)
#define EXYNOS3_CLKDIV_STAT_GDR_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_GDR_MASK		(0x1 << EXYNOS3_CLKDIV_STAT_GDR_SHIFT)
#define SRC_CPU					EXYNOS3_CPU_ISP_REG(0x4200)
#define EXYNOS3_CLK_MUX_STAT_CPU		EXYNOS3_CPU_ISP_REG(0x4400)
#define EXYNOS3_CLK_DIV_CPU0			EXYNOS3_CPU_ISP_REG(0x4500)
#define EXYNOS3_CLK_DIV_CPU1			EXYNOS3_CPU_ISP_REG(0x4504)
#define EXYNOS3_CLK_DIV_STAT_CPU0		EXYNOS3_CPU_ISP_REG(0x4600)
#define EXYNOS3_CLK_DIV_STAT_CPU1		EXYNOS3_CPU_ISP_REG(0x4604)
#define EXYNOS3_ARM_EMA_CTRL			EXYNOS3_CPU_ISP_REG(0x5008)
#define EXYNOS3_ARM_EMA_STATUS			EXYNOS3_CPU_ISP_REG(0x500C)
#define EXYNOS3_PWR_CTRL			EXYNOS3_CPU_ISP_REG(0x5020)
#define EXYNOS3_PWR_CTRL2			EXYNOS3_CPU_ISP_REG(0x5024)
#define EXYNOS3_CLKDIV_ISP0			EXYNOS3_CPU_ISP_REG(0x8300)
#define EXYNOS3_CLKDIV_ISP1			EXYNOS3_CPU_ISP_REG(0x8304)
#define EXYNOS3_CLKDIV_STAT_ISP0		EXYNOS3_CPU_ISP_REG(0x8400)
#define EXYNOS3_CLKDIV_STAT_ISP1		EXYNOS3_CPU_ISP_REG(0x8404)
#define EXYNOS3_CLKGATE_BUS_ISP0		EXYNOS3_CPU_ISP_REG(0x8700)
#define EXYNOS3_CLKGATE_BUS_ISP1		EXYNOS3_CPU_ISP_REG(0x8704)
#define EXYNOS3_CLKGATE_BUS_ISP2		EXYNOS3_CPU_ISP_REG(0x8708)
#define EXYNOS3_CLKGATE_BUS_ISP3		EXYNOS3_CPU_ISP_REG(0x870C)

#define EXYNOS3_CLKGATE_IP_ISP0			EXYNOS3_CPU_ISP_REG(0x8800)
#define EXYNOS3_CLKGATE_IP_ISP1			EXYNOS3_CPU_ISP_REG(0x8804)
#define EXYNOS3_CLKGATE_SCLK_ISP		EXYNOS3_CPU_ISP_REG(0x8900)

/* ISP */
#define DIV_ISP0				EXYNOS3_CPU_ISP_REG(0x8300)
#define DIV_ISP1				EXYNOS3_CPU_ISP_REG(0x8304)
#define DIV_STAT_ISP0				EXYNOS3_CPU_ISP_REG(0x8400)
#define DIV_STAT_ISP1				EXYNOS3_CPU_ISP_REG(0x8404)
#define GATE_BUS_ISP0				EXYNOS3_CPU_ISP_REG(0x8700)
#define GATE_BUS_ISP1				EXYNOS3_CPU_ISP_REG(0x8704)
#define GATE_BUS_ISP2				EXYNOS3_CPU_ISP_REG(0x8708)
#define GATE_BUS_ISP3				EXYNOS3_CPU_ISP_REG(0x870C)

#define GATE_IP_ISP0				EXYNOS3_CPU_ISP_REG(0x8800)
#define GATE_IP_ISP1				EXYNOS3_CPU_ISP_REG(0x8804)
#define GATE_IP_SCLK_ISP			EXYNOS3_CPU_ISP_REG(0x8900)
#define EXYNOS3_CLKOUT_CMU_ISP			EXYNOS3_CPU_ISP_REG(0x8A00)
#define EXYNOS3_CLKOUT_CMU_ISP_DIV_STAT		EXYNOS3_CPU_ISP_REG(0x8A04)

#define EXYNOS3_CMU_ISP_SPARE0			EXYNOS3_CPU_ISP_REG(0x8B00)
#define EXYNOS3_CMU_ISP_SPARE1			EXYNOS3_CPU_ISP_REG(0x8B04)
#define EXYNOS3_CMU_ISP_SPARE2			EXYNOS3_CPU_ISP_REG(0x8B08)
#define EXYNOS3_CMU_ISP_SPARE3			EXYNOS3_CPU_ISP_REG(0x8B0C)

/* MIF_R PART/ACP PART */
#define EXYNOS3_CLKSRC_MASK_ACP			EXYNOS3_MIF_R_REG(0x0304)
#define EXYNOS3_CLKSRC_ACP			EXYNOS3_MIF_R_REG(0x0300)
#define EXYNOS3_CLKDIV_ACP0			EXYNOS3_MIF_R_REG(0x0500)
#define EXYNOS3_CLKDIV_ACP1			EXYNOS3_MIF_R_REG(0x0504)
#define EXYNOS3_CLKDIV_STAT_ACP0		EXYNOS3_MIF_R_REG(0x0600)
#define EXYNOS3_CLKDIV_STAT_ACP1		EXYNOS3_MIF_R_REG(0x0604)
#define GATE_IP_ACP0				EXYNOS3_MIF_R_REG(0x0900)

#define EXYNOS3_CLKDIV_ACP_SHIFT		(0)
#define EXYNOS3_CLKDIV_ACP_MASK			(0x7 << EXYNOS3_CLKDIV_ACP_SHIFT)
#define EXYNOS3_CLKDIV_ACP_PCLK_SHIFT		(4)
#define EXYNOS3_CLKDIV_ACP_PCLK_MASK		(0x7 << EXYNOS3_CLKDIV_ACP_PCLK_SHIFT)
#define EXYNOS3_CLKDIV_ACP_DMC_SHIFT		(8)
#define EXYNOS3_CLKDIV_ACP_DMC_MASK		(0x7 << EXYNOS3_CLKDIV_ACP_DMC_SHIFT)
#define EXYNOS3_CLKDIV_ACP_DMCD_SHIFT		(12)
#define EXYNOS3_CLKDIV_ACP_DMCD_MASK		(0x7 << EXYNOS3_CLKDIV_ACP_DMCD_SHIFT)
#define EXYNOS3_CLKDIV_ACP_DMCP_SHIFT		(16)
#define EXYNOS3_CLKDIV_ACP_DMCP_MASK		(0x7 << EXYNOS3_CLKDIV_ACP_DMCP_SHIFT)

#define EXYNOS3_CLKDIV_STAT_ACP_DMCP_SHIFT	(16)
#define EXYNOS3_CLKDIV_STAT_ACP_DMCP_MASK	(0x1 << EXYNOS3_CLKDIV_STAT_ACP_DMCP_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACP_DMCD_SHIFT	(12)
#define EXYNOS3_CLKDIV_STAT_ACP_DMCD_MASK	(0x1 << EXYNOS3_CLKDIV_STAT_ACP_DMCD_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACP_DMC_SHIFT	(8)
#define EXYNOS3_CLKDIV_STAT_ACP_DMC_MASK	(0x1 << EXYNOS3_CLKDIV_STAT_ACP_DMC_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACP_PCLK_SHIFT	(4)
#define EXYNOS3_CLKDIV_STAT_ACP_PCLK_MASK	(0x1 << EXYNOS3_CLKDIV_STAT_ACP_PCLK_SHIFT)
#define EXYNOS3_CLKDIV_STAT_ACP_SHIFT		(0)
#define EXYNOS3_CLKDIV_STAT_ACP_MASK		(0x1 << EXYNOS3_CLKDIV_STAT_ACP_SHIFT)

#endif
